### ISSUE TITLE
一张图片中出现两个LSB星系

### ISSUE THREAD

**Issue by kongkk233** [wannaAC/LSB_Detetion#1]
**关于文中提到的合并我有些疑惑，请问应该如何合并呢**

**Comment by onemapl3** [comment]
YOLOv3的输入是RGB三通道的图像，意味着我们需要把单通道的图像变成三通道（即一个像素涵盖R\G\B三种颜色灰度的数值）。关于合并的方法，可参考cv2中的merge和numpy中的dstack方法
